name: ServerPlugin
version: '${project.version}'
main: com.burchard36.cloudlite.ServerPlugin
api-version: 1.19
softdepend:
  - MMOItems
  - AureliumSkills
depend:
  - WorldGuard
commands:
  skipsong:
    aliases:
      - songskip
      - skip
      - nextsong
      - songnext
    description: "Skips you to the next song in queue"
  musicgui:
    aliases:
      - music
      - musicgui
      - songs
      - songlist
      - songgui
      - songui
    description: "Displays the Songs GUI"
  compress:
    aliases:
      - compressgui
      - cgui
    description: "Opens the AutoCompressorChoice GUI"
  reloadserver:
    description: "reloads all the modules configuration values"
  upgradeitem:
    aliases:
      - itemupgrade
      - iupgrade
      - upgrade
      - upgradei
      - mmoupgrade
      - upgradehand
      - handupgrade
    description: "Opens an upgrade GUI for the player if they are holding an upgradeable MMOItem tool."