name: MusePluse
version: '${project.version}'
main: com.burchard36.musepluse.MusePluse
api-version: 1.19
commands:
  skipsong:
    aliases:
      - songskip
      - skip
      - nextsong
      - songnext
    description: "Skips you to the next song in queue"
  musicgui:
    aliases:
      - music
      - musicgui
      - songs
      - songlist
      - songgui
      - songui
    description: "Displays the Songs GUI"
libraries:
  - 'net.bramp.ffmpeg:ffmpeg:0.7.0'